<?php

/**
 * @file
 * Defines a Notifications vocabulary subscription type, very minimally.
 *
 * We could actually do without the 'subscriptions' $op of the
 * hook_notifications_node_object(). This is left in because it adds a bit of
 * interface (subscription links in nodes) that our audience may previously
 * have used as their main subscription method.
 */

/**
 * Implementation of hook_notifications.
 *
 * Defines a vocabulary subscription type and its single field, also called
 * vocabulary.
 * 
 */
function notifications_vocabulary_1_notifications($op, &$arg0 = NULL, $arg1 = NULL, $arg2 = NULL) {

  switch ($op) {
    case 'subscription types' :
      //dsm( 'subscription types' );
    
      $types['vocabulary'] = array(
        'event_type' => 'node',  // This will be for node events (insert, update, comment...)
        'title' => t('Vocabulary'),
        'fields' => array('vocabulary'), // These are the condition fields this subscription needs, in this case just the vid
        'description' => t('Subscribe to all content tagged with a term of a vocabulary.'),
      );
      return $types;

    break;
    
    case 'subscription fields' :
      //dsm( 'subscription fields' );
    
      $fields['vocabulary'] = array(
        'name' => t('Vocabulary'),
        'field' => 'vocabulary', // This seems to relate to case 'query'. See below in this fn.
        'type' => 'int',
        // This one should return an array of vid => name. Wil be used when displaying the subscription for naming the value
        // and for a drop down field when creating a subscription with this field
        'options callback' => '_notifications_vocabulary_1_vocabulary_field_options',
      );
      return $fields;
    
    break;
  }
}

/**
 * Get a list of possible options for the 'vocabulary' subscription field.
 * 
 * @return
 *   An array of all vocabularies in the form ( vid => name )
 */
function _notifications_vocabulary_1_vocabulary_field_options() {
  $vocabs = taxonomy_get_vocabularies();
  $options = array();
  foreach ( $vocabs as $vocab ) {
    $options[$vocab->vid] = $vocab->name;
  }
  return $options;
}

/**
 * Implementation of hook_notifications_object_node()
 */
function notifications_vocabulary_1_notifications_object_node($op, $node, $account = NULL) {
  dsm( 'notifications_vocabulary_1_content_notifications_object_node - ' . $op );

  switch ($op) {
    case 'conditions':

      $conditions = array();

      // At the time that this hook op is called, $node->taxonomy is just an
      // array of taxonomy term IDs.
      foreach ( $node->taxonomy as $tid ) {
        $term = taxonomy_get_term( $tid );
        $conditions['vocabulary'][] = $term->vid;
      }

      return $conditions;

    break;

    case 'subscriptions':
    
      // Return available subscription options for this node and this user account
      $options = array();
      if (notifications_subscription_type_enabled('vocabulary')) {
        
        $vids = array();

        // At the time that this hook op is called, $node->taxonomy is an array
        // of taxonomy term objects.
        foreach( $node->taxonomy as $term ) {
          $vids[$term->vid] = $term->vid;
        }
        
        foreach ( $node->taxonomy as $term ) {
          $vocab = taxonomy_vocabulary_load( $term->vid );
          $options[] = array(
            'name' => t('Posts tagged from vocabulary "@vocab"', array('@vocab' => $vocab->name )),
            'type' => 'vocabulary',
            'fields' => array('vocabulary' => $vid),
          );
        }
      }
      return $options;
      
    break;
  }
}


  /**
   * Implementation of hook_notifications.
   *
   * Implements a new subscription type for a given Topic in a given group.
   */
  function hoky_notifications($op, &$arg0 = NULL, $arg1 = NULL, $arg2 = NULL) {

    switch ($op) {
      case 'subscription types' :
      
        $types['network_topic'] = array(
        
          // This will be for node events (insert, update, comment...)
          'event_type' => 'node',
          
          'title' => t('Network topic'),
          
          // New permission must be defined in a hook_perm
          'access' => 'subscribe to network topic',
          
          // A page for a user to manage their Network topic subscriptions.
          // The same path must also be defined by a menu item in a hook_menu.
          'user page' => 'user/%user/notifications/network_topic',
          
          // These are the condition fields this subscription needs, in this case just the vid
          'fields' => array( /*'network',*/ 'topic'),
          
          'description' => t('Subscribe to content, in a given network, tagged with a specific term.'),
        );
        return $types;

      break;
      
      case 'subscription fields' :
      
        $fields['network'] = array(
        
          'name' => t('Network'),
          
          // Okay this seems a bit recursive; a field within a field.
          // I'm going to assume for now that this is the "machine name" of the field.
          'field' => 'network',
          
          // A very raw exposure to type?!
          'type' => 'int',
          
          // This one should return an array of vid => name. Wil be used when displaying the subscription for naming the value
          // and for a drop down field when creating a subscription with this field
          'options callback' => '_vocabulary_notifications_options',
        );
        return $fields;
      
      break;
    }
  }


















